### ISSUE TITLE
change object test for bandwidth

### ISSUE THREAD

**Issue by rBatt** [AlexanderButyaev/kern_smooth#1]
Consider changing [this line](https://github.com/AlexanderButyaev/kern_smooth/blob/master/kern_smooth/ks.py#L127) to be the following:

```
if bandwidth is None:
```

I had trouble passing in my own 2 bandwidths as an array until I tried that change

**Comment by AlexanderButyaev** [comment]
Hey @rBatt,

What kind of problem did you get with this line? I do agree that is None should be generally used, however, I don't understand how it might be a cause of the problem...

**Comment by rBatt** [comment]
You get an error if you pass an array. 

Try doing 

np.array([0,1]) == None

I believe that raises an error (on my phone at the moment). There are numpy array methods to handle that type of test (a.any() is mentioned in the error message), but that method won’t generalize to the scenario for which None is passed in as the bandwidth.

**Comment by AlexanderButyaev** [comment]
Makes sense. Totally forgot about numpy arrays... Fixed. Thanks!
